<div class="banner big-banner" 	style="background-image: url(<?php echo $block->getViewFileUrl('images/content/slides/image1.jpg'); ?>)">
    <div class="banner-internal">
        <div class="banner-content">
            <div class="slide-cms">
                <h3 class="slide-cms-tag">NEW COLLECTION</h3>
                <h2 class="slide-cms-title">Classic stylish
                <br>gloves for men</h2>
                <a href="#" class="action on-dark-bg primary">View and shop now</a>
            </div>
        </div>
    </div>
</div>
