<?php
/**
 * @package Divante/rapid
 * @author Kacper Chara <kchara@divante.pl>
 * @copyright 2018 Divante Sp. z o.o.
 * @license See LICENSE_DIVANTE.txt for license details.
 */

/**
 * @var $block Magento\Framework\View\Element\Template
 */
?>

<h2 class="second-style-heading line-on-sides">
    <span><?php echo __('Popular Brands'); ?></span>
</h2>

<div class="class="simple-picture-list logos-of-brands"" id="owl-demo" data-mage-init='{
"OwlCarousel":{
        "autoPlay": 3000,
        "items" : 5,
        "itemsDesktop" : [1199,3],
        "itemsDesktopSmall" : [979,3],
        "autoHeight":false,
        "responsiveClass": true,
        "dots": true
       
    }
}'>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand1.jpg'); ?>" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand2.jpg'); ?>" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand3.jpg'); ?>" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand4.jpg'); ?>" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand5.jpg'); ?>" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand6.jpg'); ?>" alt="illustration"/></a></div>

</div>

<!-- <ul class="simple-picture-list logos-of-brands" >
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand1.jpg'); ?>" alt="illustration"/></a></li>
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand2.jpg'); ?>" alt="illustration"/></a></li>
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand3.jpg'); ?>" alt="illustration"/></a></li>
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand4.jpg'); ?>" alt="illustration"/></a></li>
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand5.jpg'); ?>" alt="illustration"/></a></li>
    <li class="item"><a href="#"><img src="<?php echo $block->getViewFileUrl('images/content/brands/logo-brand6.jpg'); ?>" alt="illustration"/></a></li>
</ul>

 -->
<div class="banners">
    <div class="banners-row">
        <div class="banner banner-1-2" style="background-image: url(<?php echo $block->getViewFileUrl('images/content/banners/555x254.png'); ?>)">
            <div class="banner-content valign-top">
                <h4 class="banner-tag">Outlet</h4>
                <h3 class="banner-title">What is Lorem Ipsum?</h3>
                <p class="banner-description">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                <a href="#" class="action on-dark-bg primary">SHOP NOW</a>
            </div>
        </div>

        <div class="banner banner-1-2" style="background-image: url(<?php echo $block->getViewFileUrl('images/content/banners/555x254.png'); ?>)">
            <div class="banner-content valign-top">
                <h4 class="banner-tag">Outlet</h4>
                <h3 class="banner-title">What is Lorem Ipsum? <br />Lorem Ipsum</h3>
                <p class="banner-description">is simply dummy text of the printing and typesetting industry.</p>
                <a href="#" class="action on-dark-bg primary">SHOP NOW</a>
            </div>
        </div>
    </div>
    
    <div class="banner banner-1-1" style="background-image: url(<?php echo $block->getViewFileUrl('images/content/banners/1140x584.png'); ?>)">
        <div class="banner-content valign-bottom">
            <h4 class="banner-tag">New</h4>
            <h3 class="banner-title">What is Lorem Ipsum? <br />Lorem Ipsum</h3>
            <p class="banner-description">is simply dummy text of the printing and typesetting industry..</p>
            <a href="#" class="action on-dark-bg primary">View and shop now</a>
        </div>
    </div>
</div>
