<script type="text/javascript">
    require(['jf']);
</script>
<div id="owl-demo" data-mage-init='{
"OwlCarousel":{
        "autoPlay": 3000,
        "items" : 2,
        "itemsDesktop" : [1199,3],
        "itemsDesktopSmall" : [979,3],
        "autoHeight":false,
        "responsiveClass": true

    }
}'>
 <div class="item"><img src="https://www.baby-g.com/resource/img/home_banner/BG_FB_201903_Cover.jpg" alt="Owl Image"></div>
 <div class="item"><img src="https://www.baby-g.com/resource/img/home_banner/baby-g-35th.gif" alt="Owl Image"></div>
 <div class="item"><img src="https://instax.com/wp-content/uploads/2017/03/top-share_1280-480-1.jpg" alt="Owl Image"></div>
 <div class="item"><img src="https://instax.com/wp-content/uploads/2018/08/sq6_bn_20180925_pc-1280-480.jpg"></div>

</div>
