<div id="fromLayout-component" data-bind="scope:'scriptName'">
<!-- echo $block->getJsLayout(); output      

    {
        "components":
        {
            "scriptName":
            {
                "component":"Magestudy_Customjs\/js\/from_layout_example",
                "config":
                {
                    "first":"FirstValueFromXml",
                    "second":"SecondValueFromXml"
                }
            }
        }
    } -->
    <script type="text/x-magento-init">
    {
        "#fromLayout-component": {
            "Magento_Ui/js/core/app":  <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
    </script>
    <span data-bind="text:getFirstValue()"></span>
    <br>
    <span data-bind="text:getSecondValue()"></span>
</div>
