<?php
/** @var \Magestudy\Widget\Block\Widget\SampleBlock\PopularBrands $block */
?>
<h2 class="second-style-heading line-on-sides">
    <span><?php echo __('Popular Brands'); ?></span>
</h2>

<div class="simple-picture-list logos-of-brands" id="owl-demo" data-mage-init='{
"OwlCarousel":{
        "autoPlay": 3000,
        "items" : 5,
        "itemsDesktop" : [1199,3],
        "itemsDesktopSmall" : [979,3],
        "autoHeight":false,
        "responsiveClass": false,
        "dots": true
    }
}'>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/XIAOMI.jpg" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/ASUS.jpg" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/ACER.jpg" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/DELL.jpg" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/CANON.jpg" alt="illustration"/></a></div>
 <div class="item"><a href="#"><img src="https://dcwr92jbyjp0p.cloudfront.net/IMAGES/storeapp/store_brand_banners/EPSON.jpg" alt="illustration"/></a></div>

</div>
